book/urls.py
from django.urls import path
from .views import (
    HomeView,
    AllBookView,
    PhysicalBookListView,
    ElectronicBookListView,
    AudioBookListView,
    AuthorListView,
    TranslatorListView,
    TellerListView,
    PublisherListView,
    CategoryListView,
    PhysicalBookCreateView,
    ElectronicBookCreateView,
    AudioBookCreateView,
    PhysicalBookUpdateView,
    ElectronicBookUpdateView,
    AudioBookUpdateView,
    PhysicalBookDeleteView,
    ElectronicBookDeleteView,
    AudioBookDeleteView,
    AuthorCreateView,
    TranslatorCreateView,
    TellerCreateView,
    AuthorUpdateView,
    TranslatorUpdateView,
    TellerUpdateView,
    AuthorDeleteView,
    TranslatorDeleteView,
    TellerDeleteView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    PublisherCreateView,
    PublisherUpdateView,
    PublisherDeleteView,
)

app_name = 'book'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('books/', AllBookView.as_view(), name='allbook'),
    path('physicalbook/', PhysicalBookListView.as_view(), name='physicalbook'),
    path('physicalbook/create/', PhysicalBookCreateView.as_view(), name='physicalbook_create'),
    path('physicalbook/update/<int:pk>', PhysicalBookUpdateView.as_view(), name='physicalbook_update'),
    path('physicalbook/delete/<int:pk>', PhysicalBookDeleteView.as_view(), name='physicalbook_delete'),
    path('electronicbook/', ElectronicBookListView.as_view(), name='electronicbook'),
    path('electronicbook/create/', ElectronicBookCreateView.as_view(), name='electronicbook_create'),
    path('electronicbook/update/<int:pk>', ElectronicBookUpdateView.as_view(), name='electronicbook_update'),
    path('electronicbook/delete/<int:pk>', ElectronicBookDeleteView.as_view(), name='electronicbook_delete'),
    path('audiobook/', AudioBookListView.as_view(), name='audiobook'),
    path('audiobook/create/', AudioBookCreateView.as_view(), name='audiobook_create'),
    path('audiobook/update/<int:pk>', AudioBookUpdateView.as_view(), name='audiobook_update'),
    path('audiobook/delete/<int:pk>', AudioBookDeleteView.as_view(), name='audiobook_delete'),
    path('author/', AuthorListView.as_view(), name='author'),
    path('author/create/', AuthorCreateView.as_view(), name='author_create'),
    path('author/update/<int:pk>', AuthorUpdateView.as_view(), name='author_update'),
    path('author/delete/<int:pk>', AuthorDeleteView.as_view(), name='author_delete'),
    path('translator/', TranslatorListView.as_view(), name='translator'),
    path('translator/create', TranslatorCreateView.as_view(), name='translator_create'),
    path('translator/update/<int:pk>', TranslatorUpdateView.as_view(), name='translator_update'),
    path('translator/delete/<int:pk>', TranslatorDeleteView.as_view(), name='translator_delete'),
    path('teller/', TellerListView.as_view(), name='teller'),
    path('teller/create', TellerCreateView.as_view(), name='teller_create'),
    path('teller/update/<int:pk>', TellerUpdateView.as_view(), name='teller_update'),
    path('teller/delete/<int:pk>', TellerDeleteView.as_view(), name='teller_delete'),
    path('publisher/', PublisherListView.as_view(), name='publisher'),
    path('publisher/create/', PublisherCreateView.as_view(), name='publisher_create'),
    path('publisher/update/<int:pk>', PublisherUpdateView.as_view(), name='publisher_update'),
    path('publisher/delete/<int:pk>', PublisherDeleteView.as_view(), name='publisher_delete'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
    path('accounts/', include('allauth.urls')),
]


# add static url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/forms.py
from django.forms import ModelForm
from book.widgets import CustomeClearableFileInput
from book.models import AudioBook, PhysicalBook, ElectronicBook

class PhysicalBookCreateUpdateForm(ModelForm):

    class Meta:
        model = PhysicalBook
        fields = ['picture', 'title', 'author', 'translator', 'language_book', 'user_rate', 'category', 'price', 'price_unit', 'user_description', 'book_url', 'publisher', 'pages_readed', 'pages', 'read_status', 'platform']
        widgets = {
            'picture': CustomeClearableFileInput(),
        }


class ElectronicBookCreateUpdateForm(ModelForm):

    class Meta:
        model = ElectronicBook
        fields = ['picture', 'title', 'author', 'translator', 'language_book', 'user_rate', 'category', 'price', 'price_unit', 'user_description', 'book_url', 'publisher', 'pages_readed', 'pages', 'read_status', 'platform', 'book_file']
        widgets = {
            'picture': CustomeClearableFileInput(),
        }


class AudioBookCreateUpdateForm(ModelForm):

    class Meta:
        model = AudioBook
        fields = ['picture', 'title', 'author', 'translator', 'language_book', 'user_rate', 'category', 'price', 'price_unit', 'user_description', 'book_url', 'publisher',  'teller', 'episode', 'season', 'listen_status', 'platform', 'book_file']
        widgets = {
            'picture': CustomeClearableFileInput(),
        }

book/views.py
import random
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from book.forms import (
    AudioBookCreateUpdateForm,
    PhysicalBookCreateUpdateForm,
    ElectronicBookCreateUpdateForm,
)
from django.views.generic import (
    ListView,
    TemplateView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import (
    PhysicalBook,
    ElectronicBook,
    AudioBook,
    Author,
    Translator,
    Teller,
    Publisher,
    Category,
)

# Create your views here.
class HomeView(TemplateView):
    template_name = 'book/index.html'


class AllBookView(LoginRequiredMixin, TemplateView):

    def get(self, request, **kwargs):
        all_book = []

        physicalbook = PhysicalBook.objects.filter(user=self.request.user).all()
        electronicbook = ElectronicBook.objects.filter(user=self.request.user).all()
        audiobook = AudioBook.objects.filter(user=self.request.user).all()

        for book in physicalbook:
            all_book.append({
                'picture': book.picture,
                'title': book.title,
                'show_author': book.show_author,
                'show_translator': book.show_translator,
                'show_category': book.show_category,
                'show_publisher': book.show_publisher,
                'show_user_rate': book.show_user_rate,
                'status': book.get_read_status_display(),
                'platform': book.get_platform_display(),
                'type': 'فیزیکی',
                'update_url': reverse('book:physicalbook_update', kwargs={'pk':book.pk}),
                'delete_url': reverse('book:physicalbook_delete', kwargs={'pk':book.pk}),
            })
        
        for book in electronicbook:
            all_book.append({
                'picture': book.picture,
                'title': book.title,
                'show_author': book.show_author,
                'show_translator': book.show_translator,
                'show_category': book.show_category,
                'show_publisher': book.show_publisher,
                'show_user_rate': book.show_user_rate,
                'status': book.get_read_status_display(),
                'platform': book.get_platform_display(),
                'type': 'الکترونیکی',
                'update_url': reverse('book:electronicbook_update', kwargs={'pk':book.pk}),
                'delete_url': reverse('book:electronicbook_delete', kwargs={'pk':book.pk}),
            })

        for book in audiobook:
            all_book.append({
                'picture': book.picture,
                'title': book.title,
                'show_author': book.show_author,
                'show_translator': book.show_translator,
                'show_category': book.show_category,
                'show_publisher': book.show_publisher,
                'show_user_rate': book.show_user_rate,
                'status': book.get_listen_status_display(),
                'platform': book.get_platform_display(),
                'type': 'صوتی',
                'update_url': reverse('book:audiobook_update', kwargs={'pk':book.pk}),
                'delete_url': reverse('book:audiobook_delete', kwargs={'pk':book.pk}),
            })

        random.shuffle(all_book)
        context = {
            'all_book': all_book
        }

        return render(request, 'book/books.html', context)


class PhysicalBookListView(LoginRequiredMixin, ListView):
    model = PhysicalBook

    def get_queryset(self):
        return PhysicalBook.objects.filter(user=self.request.user).all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ElectronicBookListView(LoginRequiredMixin, ListView):
    model = ElectronicBook

    def get_queryset(self):
        return ElectronicBook.objects.filter(user=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AudioBookListView(LoginRequiredMixin, ListView):
    model = AudioBook

    def get_queryset(self):
        return AudioBook.objects.filter(user=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AuthorListView(LoginRequiredMixin, ListView):
    model = Author
    template_name = 'book/person_list.html'

    def get_queryset(self):
        return Author.objects.filter(user=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_title'] = "نویسندگان"
        context['update_url'] = 'book:author_update'
        context['delete_url'] = 'book:author_delete'
        return context


class TranslatorListView(LoginRequiredMixin, ListView):
    model = Translator
    template_name = 'book/person_list.html'

    def get_queryset(self):
        return Translator.objects.filter(user=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_title'] = "مترجمین"
        context['update_url'] = 'book:translator_update'
        context['delete_url'] = 'book:translator_delete'
        return context


class TellerListView(LoginRequiredMixin, ListView):
    model = Teller
    template_name = 'book/person_list.html'

    def get_queryset(self):
        return Teller.objects.filter(user=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_title'] = "گویندگان"
        context['update_url'] = 'book:teller_update'
        context['delete_url'] = 'book:teller_delete'
        return context


class PublisherListView(LoginRequiredMixin, ListView):
    model = Publisher

    def get_queryset(self):
        return Publisher.objects.filter(user=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PhysicalBookCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = PhysicalBook
    form_class = PhysicalBookCreateUpdateForm
    template_name = 'book/physicalbook_create_update.html'
    success_message = "کتاب فیزیکی با موفقیت افزوده شد"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['form'].fields['author'].queryset = Author.objects.filter(user=self.request.user).all()
        context['form'].fields['translator'].queryset = Translator.objects.filter(user=self.request.user).all()
        context['form'].fields['category'].queryset = Category.objects.filter(user=self.request.user).all()
        context['form'].fields['publisher'].queryset = Publisher.objects.filter(user=self.request.user).all()
        return context


class PhysicalBookUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = PhysicalBook
    form_class = PhysicalBookCreateUpdateForm
    template_name = 'book/physicalbook_create_update.html'
    success_message = "کتاب فیزیکی با موفقیت ویرایش شد"

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['form'].fields['author'].queryset = Author.objects.filter(user=self.request.user).all()
        context['form'].fields['translator'].queryset = Translator.objects.filter(user=self.request.user).all()
        context['form'].fields['category'].queryset = Category.objects.filter(user=self.request.user).all()
        context['form'].fields['publisher'].queryset = Publisher.objects.filter(user=self.request.user).all()
        return context


class PhysicalBookDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = PhysicalBook
    success_url = reverse_lazy('book:physicalbook')
    template_name = 'book/book_confirm_delete.html'
    success_message = "کتاب فیزیکی با موفقیت حذف شد"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PhysicalBookDeleteView, self).delete(request, *args, **kwargs)


class ElectronicBookCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = ElectronicBook
    form_class = ElectronicBookCreateUpdateForm
    template_name = 'book/electronicbook_create_update.html'
    success_message = "کتاب الکترونیکی با موفقیت افزوده شد"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['form'].fields['author'].queryset = Author.objects.filter(user=self.request.user).all()
        context['form'].fields['translator'].queryset = Translator.objects.filter(user=self.request.user).all()
        context['form'].fields['category'].queryset = Category.objects.filter(user=self.request.user).all()
        context['form'].fields['publisher'].queryset = Publisher.objects.filter(user=self.request.user).all()
        return context


class ElectronicBookUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ElectronicBook
    form_class = ElectronicBookCreateUpdateForm
    template_name = 'book/electronicbook_create_update.html'
    success_message = "کتاب الکترونیکی با موفقیت ویرایش شد"

templates/book/audiobook_create_update.html
{% extends 'book/books.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main%}
<section class="content">
<div class="container-fluid">
	<div class="row">
		<div class="card card-primary form-card">
			<div class="card-header">
			  	<h3 class="card-title">کتاب صوتی</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
				<div class="card-body">
					<div class="row">
						<div class="col-6">{{ form.picture|as_crispy_field }}</div>
                        <div class="col-6">{{ form.book_file|as_crispy_field }}</div>
					</div>
					<div class="row">
						<div class="col-6">{{ form.title|as_crispy_field }}</div>
						<div class="col-6">{{ form.category|as_crispy_field }}
							<a href="{% url 'book:category_create' %}" title="افزودن دسته‌بندی جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
					</div>
					<div class="row">
						<div class="col-4">{{ form.author|as_crispy_field }}
							<a href="{% url 'book:author_create' %}" title="افزودن نویسنده جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
						<div class="col-4">{{ form.translator|as_crispy_field }}
							<a href="{% url 'book:translator_create' %}" title="افزودن مترجم جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
						<div class="col-4">{{ form.teller|as_crispy_field }}
							<a href="{% url 'book:teller_create' %}" title="افزودن گوینده جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
					</div>
					<div class="row">
						<div class="col-6">{{ form.book_url|as_crispy_field }}</div>
						<div class="col-6">{{ form.publisher|as_crispy_field }}
							<a href="{% url 'book:publisher_create' %}" title="افزودن ناشر جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
					</div>
					<div class="row">
						<div class="col-12">{{ form.user_description|as_crispy_field }}</div>
					</div>
					<div class="row">
						<div class="col-3">{{ form.listen_status|as_crispy_field }}</div>
						<div class="col-3">{{ form.platform|as_crispy_field }}</div>
						<div class="col-3">{{ form.episode|as_crispy_field }}</div>
						<div class="col-3">{{ form.season|as_crispy_field }}</div>
					</div>
					<div class="row">
						<div class="col-3">{{ form.price|as_crispy_field}}</div>
						<div class="col-3">{{ form.price_unit|as_crispy_field}}</div>
						<div class="col-3">{{ form.language_book|as_crispy_field}}</div>
						<div class="col-3">{{ form.user_rate|as_crispy_field}}</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">تایید</button>
				</div>
			</form>
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/book/book_confirm_delete.html
{% extends 'book/books.html' %}
{% load static %}
{% block main%}
<section class="content">
<div class="container-fluid">
	<div class="row">
        <div class="col-md-8 text-center mx-auto">
            <div class="card card-danger">
                <div class="card-header">
                <h3 class="card-title mb-0 float-left">حذف کتاب</h3>
                </div>
                <div class="card-body py-4">
                    <form method="post">{% csrf_token %}
                        <p class="py-2">مطمئنی میخوای کتاب «{{ object }}» از «{{object.show_author}}» رو حذف کنی؟</p>
                        <input type="submit" class="btn btn-danger" value="حذف">
                    </form>
                </div>
            </div>
        </div>
	</div>
</div>
</section>
{% endblock %}

templates/book/books.html
{% extends 'book/base.html' %}
{% load static %}

{% block title %}پروفایل کاربری{% endblock %}

{% block navbar %}
    {% include 'book/navbar.html' %}
{% endblock %}

{% block sidebar %}
    {% include 'book/sidebar.html' %}
{% endblock %}

{% block header%}
    {% include 'book/header.html' %}
{% endblock %}


{% block main %}
    {% include 'book/main.html' %}
{% endblock %}


{% block footer %}
    {% include 'book/footer.html' %}
{% endblock %}

templates/book/category_create_update.html
{% extends 'book/books.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main%}
<section class="content">
<div class="container-fluid">
	<div class="row">
		<div class="card card-primary form-card">
			<div class="card-header">
			  	<h3 class="card-title">دسته‌بندی</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form role="form" method="post">{% csrf_token %}
				<div class="card-body">
					<div class="row">
						<div class="col-6">{{ form.title|as_crispy_field }}</div>
                        <div class="col-6">{{ form.parent|as_crispy_field }}</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">تایید</button>
				</div>
			</form>
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/book/category_list.html
{% extends 'book/books.html' %}
{% load static %}
{% block main%}
<section class="content">
<div class="container-fluid">
	{% include 'book/messages.html' %}
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">دسته‌بندی ها</h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body table-responsive p-0" style="height: 300px;">
					<table class="table table-head-fixed">
						<thead>
							<tr>
								<th>ردیف</th>
								<th>دسته‌بندی ها</th>
								<th>زیر دسته</th>
								<th>عملیات</th>
							</tr>
						</thead>
						<tbody>
							{% for category in object_list %}
							<tr>
								<td>{{ forloop.counter }}</td>
								<td>{{ category.title }}</td>
								<td>{{ category.show_parent }}</td>
								<td><a href="{% url 'book:category_update' category.pk %}" class="badge badge-primary">ویرایش</a>
									<a href="{% url 'book:category_delete' category.pk %}" class="badge badge-danger">حذف</a></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<!-- /.card-body -->
			</div>
			<!-- /.card -->
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/book/electronicbook_create_update.html
{% extends 'book/books.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main%}
<section class="content">
<div class="container-fluid">
	<div class="row">
		<div class="card card-primary form-card">
			<div class="card-header">
			  	<h3 class="card-title">کتاب الکتریکی</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
				<div class="card-body">
					<div class="row">
						<div class="col-6">{{ form.picture|as_crispy_field }}</div>
                        <div class="col-6">{{ form.book_file|as_crispy_field }}</div>
					</div>
					<div class="row">
						<div class="col-6">{{ form.title|as_crispy_field }}</div>
						<div class="col-6">{{ form.category|as_crispy_field }}
							<a href="{% url 'book:category_create' %}" title="افزودن دسته‌بندی جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
					</div>
					<div class="row">
						<div class="col-6">{{ form.author|as_crispy_field }}
							<a href="{% url 'book:author_create' %}" title="افزودن نویسنده جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
						<div class="col-6">{{ form.translator|as_crispy_field }}
							<a href="{% url 'book:translator_create' %}" title="افزودن مترجم جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
					</div>
					<div class="row">
						<div class="col-6">{{ form.book_url|as_crispy_field }}</div>
						<div class="col-6">{{ form.publisher|as_crispy_field }}
							<a href="{% url 'book:publisher_create' %}" title="افزودن ناشر جدید" target="_blank">
								<img src="/static/admin/img/icon-addlink.svg" alt="اضافه کردن">
							</a>
						</div>
					</div>
					<div class="row">
						<div class="col-12">{{ form.user_description|as_crispy_field }}</div>
					</div>
					<div class="row">
						<div class="col-3">{{ form.read_status|as_crispy_field }}</div>
						<div class="col-3">{{ form.platform|as_crispy_field }}</div>
						<div class="col-3">{{ form.pages_readed|as_crispy_field }}</div>
						<div class="col-3">{{ form.pages|as_crispy_field }}</div>
					</div>
					<div class="row">
						<div class="col-3">{{ form.price|as_crispy_field}}</div>
						<div class="col-3">{{ form.price_unit|as_crispy_field}}</div>
						<div class="col-3">{{ form.language_book|as_crispy_field}}</div>
						<div class="col-3">{{ form.user_rate|as_crispy_field}}</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">تایید</button>
				</div>
			</form>
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/book/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2021-2022 <a href="http://mahigoli.com">MahiGoli.com</a>.</strong>
    All rights reserved.
</footer>

templates/book/header.html
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1 class="m-0 text-dark">لیست کتب</h1> -->
        </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

templates/book/person_create_update.html
{% extends 'book/books.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load base_tags %}
{% block main%}
<section class="content">
<div class="container-fluid">
	<div class="row">
		<div class="card card-primary form-card">
			<div class="card-header">
			  	<h3 class="card-title">{{ model_name }}</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
				<div class="card-body">
					<div class="row">
						{{ form.avatar|as_crispy_field }}
					</div>
					<div class="row">
						<div class="col-6">{{ form.first_name|as_crispy_field }}</div>
						<div class="col-6">{{ form.last_name|as_crispy_field }}</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">تایید</button>
				</div>
			</form>
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/book/publisher_list.html
{% extends 'book/books.html' %}
{% load static %}
{% block main%}
<section class="content">
<div class="container-fluid">
	{% include 'book/messages.html' %}
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">ناشران</h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body table-responsive p-0" style="height: 300px;">
					<table class="table table-head-fixed">
						<thead>
							<tr>
								<th>ردیف</th>
								<th>ناشر</th>
								<th>آدرس اینترنتی</th>
								<th>عملیات</th>
							</tr>
						</thead>
						<tbody>
							{% for publisher in object_list %}
							<tr>
								<td>{{ forloop.counter }}</td>
								<td>{{ publisher.title }}</td>
								<td>{{ publisher.url }}</td>
								<td><a href="{% url 'book:publisher_update' publisher.pk %}" class="badge badge-primary">ویرایش</a>
									<a href="{% url 'book:publisher_delete' publisher.pk %}" class="badge badge-danger">حذف</a></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<!-- /.card-body -->
			</div>
			<!-- /.card -->
		</div>
	</div>
</div>
</section>
{% endblock %}